### ISSUE TITLE
Serial comm problem

### ISSUE THREAD

**Issue by Horderf** [fuzikt/psd_mvp_control#1] opened 2024-03-28 17:28 UTC
Hi, 

Please can you help? When adding a device (e.g., PSD4) and selecting a COM port and then adding another device (e.g., MVP) and selecting another COM port, the GUI shows the same device and COM port twice versus separate devices and COM ports:

PSD4 COM 3
PSD4 COM 3

instead of 
PSD3 COM3
MVP COM4

It only communicates with the first.

Thanks in advance,

Adrian

**Comment by fuzikt** [comment] 2024-03-29 12:24
Hi Adrian,
thanks for reporting. bug fixed... try the latest release (0.2.1)

**Comment by Horderf** [comment] 2024-03-29 12:29
Thanks for the quick reply and prompt action. I’ll try it on Tuesday after the Easter holidays and will let you know.
Best regards,
Adrian

**Comment by Horderf** [comment] 2024-04-02 12:27
Hi,

It’s now working, which is great. Thank you. Could you tell me how the MVP works please with a 8-5 valve? If I want to use the MVP with 8-5 valve to select a given liquid and pull that liquid into an upstream PSD4 syringe I connect the PSD4 inlet to the outlet of the MVP4 which I think is in the 6 o’clock position on the MVP4 8-5 valve. On the software, what MVP settings and steps would I need? I don’t really understand the relationship between the options (outout valve left/right, valve port e.g., -1 and commands e.g., valve output/input/bypass) and the MVP 8-5 valve.

***@***.***

Many thanks,

Adrian

**Comment by fuzikt** [comment] 2024-04-02 13:10
Hi Adrian,
this is more question for the Hamilton support.

Up to my knowledge:
- you need to set the valve type using the DIP switches on the MVP4 body (refer to the MVP4 manual for the correct setting)
- all the commands come from the Hamilton manual, however; I don't know if all of them apply to all the valve/MVP4 combinations
- initialize: outout valve left/right - this should tell the MVP4 which port is considered to be the output (e.g. the one on the left side or the one on the right side from input - if there are only 2 ports then they are labeled by the initialization which one is input and which one is output. I don't know if this also applies for the 8-5 valve (but will not anyway affect the valve, it just labels the ports internally in the HW)
- valve output/input/bypass - these are some predefined port setup positions. E.g. if you initialized your MVP4 with output left, then the "valve output" should switch the valve to this position. Again this likely depends on the definition of the port/valve positions in the manual for a certain valve (we are using 6-6; and there the input, output, bypass sets the valve to 3 distinct positions)
- valve port e.g., -1 - this is the most universal way to use the valve (and we use it this way a well). Again depending on the valve definition (and maybe depending on the left/right initialization), the ports are labeled 1->8. Frankly, don't know if CW, CCW and which one is the 1 and which is the 8 - this has to be determined by trial/error (but in general if you already found it out, than it does not change). Then you just numerically define into which position the valve should be set and you are ready to go.
- one last thing: the SW on the comp does no know which valve is installed on the MVP4. It just sends (and gets some responses) the commands and the MVP4 is doing the rest. I.e. depending on the DIP switch positions it knows which valve is installed and how it should turn to set a certain port asked by the SW sent command. Therefore it is important to always start with an initialization (e.g. after you turn off/on the MVP4), which will set the MVP4 to correct ini  position for the commands.

Hope this helped
Tibor

**Comment by Horderf** [comment] 2024-04-02 13:20
Thanks Tibor,

I received the MVP manual almost at the same time as your reply. The Hamilton Sales person sent me the specification by mistake. The manual and your reply will be a big help.

Thanks again,

Adrian

**Comment by Horderf** [comment] 2024-04-03 14:41
Hi Tibor,

I’m able to select and pull liquids, which is great, though I’m not sure why with the 8-5 valve selector I can select only 4 using the 8-5 DIP switch setting. I wonder if the 4th DIP switch is broken. Without replacing the valve, I can set the DIP switches to a 6-5 valve and get 6 liquids. At the worst, I’ll try a 6-5 valve (which I’ve got) with a 6-5 DIP.

Just another software observation (that I’ve not had a chance to confirm because I’m not near the office/lab today) - I think the software is shutting when I try to save a program. After reopening the GUI, I can’t find a saved program.

Best,

Adrian

From: Adrian Horgan
Sent: Tuesday, April 2, 2024 2:20 PM
To: fuzikt/psd_mvp_control ***@***.***>; fuzikt/psd_mvp_control ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [fuzikt/psd_mvp_control] Serial comm problem (Issue #1)

Thanks Tibor,

I received the MVP manual almost at the same time as your reply. The Hamilton Sales person sent me the specification by mistake. The manual and your reply will be a big help.

Thanks again,

Adrian

**Comment by Horderf** [comment] 2024-04-09 14:42
Dear Tibor,

Sorry to bother you again. I’d really appreciate some help. I had it working using the program below
:
[A screenshot of a computer  Description automatically generated]

but then I came back after Easter and it wasn’t for some reason.

I assume the PSD4 commands valve_input (e.g., step 3) and valve_output (e.g., step 7) should move the PSD4 valve to input and output, respectively. If the initialise command sets valve output to right then when I edit a valve_output command I should see valve right selected. This is not the case. For example,


***@***.***

Could you explain why?

Thanks in advance,

Adrian

From: Adrian Horgan
Sent: Wednesday, April 3, 2024 3:41 PM
To: fuzikt/psd_mvp_control ***@***.***>; fuzikt/psd_mvp_control ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [fuzikt/psd_mvp_control] Serial comm problem (Issue #1)

Hi Tibor,

I’m able to select and pull liquids, which is great, though I’m not sure why with the 8-5 valve selector I can select only 4 using the 8-5 DIP switch setting. I wonder if the 4th DIP switch is broken. Without replacing the valve, I can set the DIP switches to a 6-5 valve and get 6 liquids. At the worst, I’ll try a 6-5 valve (which I’ve got) with a 6-5 DIP.

Just another software observation (that I’ve not had a chance to confirm because I’m not near the office/lab today) - I think the software is shutting when I try to save a program. After reopening the GUI, I can’t find a saved program.

Best,

Adrian

From: Adrian Horgan
Sent: Tuesday, April 2, 2024 2:20 PM
To: fuzikt/psd_mvp_control ***@***.******@***.***>>; fuzikt/psd_mvp_control ***@***.******@***.***>>
Cc: Author ***@***.******@***.***>>
Subject: RE: [fuzikt/psd_mvp_control] Serial comm problem (Issue #1)

Thanks Tibor,

I received the MVP manual almost at the same time as your reply. The Hamilton Sales person sent me the specification by mistake. The manual and your reply will be a big help.

Thanks again,

Adrian

**Comment by fuzikt** [comment] 2024-04-09 15:55
Hi Adrian,

no images (screenshots) were transferred, but I'll try to guess where the problem is. Are the DIP switches on the PSD4 set to correct valve type? If you run the single command valve_input/valve_output can you hear the valve rotation sound? Just tried on our PSD4 with Y valve and it was working correctly. Also a good thing to know: if the device gets an unexecutable command, it will simply do nothing, but not reporting back anything else than readiness for the controlling program - so for the controlling program is looks that the command finished. (this is for example different when the syringe moves - the program knows that the device is not ready and everything is grayed out).

**Comment by Horderf** [comment] 2024-04-09 18:12
Hi Tibor,

Many thanks for the reply. I should’ve thought about the DIP switches on the PSD4 (Doh!) but didn’t receive a manual either for the PSD4 so didn’t go through a guided set-up. I will try again on Thursday.

Best,

Adrian

**Comment by Horderf** [comment] 2024-04-09 18:50
PS. I've found a manual online and it says for a Y valve that DIP switches 4, 5, 6 should be Off, Off, Off, which is probably how it came - I imagine all the switches are in the Off position. Is your PSD/4 Off, Off, Off? I will need to check mine when I am back in on Thursday.

Attached are the screen prints in Word and the program.

Many thanks,

Adrian



From: Adrian Horgan
Sent: Tuesday, April 9, 2024 7:13 PM
To: fuzikt/psd_mvp_control ***@***.***>; fuzikt/psd_mvp_control ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [fuzikt/psd_mvp_control] Serial comm problem (Issue #1)

Hi Tibor,

Many thanks for the reply. I should've thought about the DIP switches on the PSD4 (Doh!) but didn't receive a manual either for the PSD4 so didn't go through a guided set-up. I will try again on Thursday.

Best,

Adrian

**Comment by Horderf** [comment] 2024-04-09 18:52
With program

From: Adrian Horgan
Sent: Tuesday, April 9, 2024 7:51 PM
To: fuzikt/psd_mvp_control ***@***.***>; fuzikt/psd_mvp_control ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [fuzikt/psd_mvp_control] Serial comm problem (Issue #1)

PS. I've found a manual online and it says for a Y valve that DIP switches 4, 5, 6 should be Off, Off, Off, which is probably how it came - I imagine all the switches are in the Off position. Is your PSD/4 Off, Off, Off? I will need to check mine when I am back in on Thursday.

Attached are the screen prints in Word and the program.

Many thanks,

Adrian



From: Adrian Horgan
Sent: Tuesday, April 9, 2024 7:13 PM
To: fuzikt/psd_mvp_control ***@***.******@***.***>>; fuzikt/psd_mvp_control ***@***.******@***.***>>
Cc: Author ***@***.******@***.***>>
Subject: RE: [fuzikt/psd_mvp_control] Serial comm problem (Issue #1)

Hi Tibor,

Many thanks for the reply. I should've thought about the DIP switches on the PSD4 (Doh!) but didn't receive a manual either for the PSD4 so didn't go through a guided set-up. I will try again on Thursday.

Best,

Adrian

**Comment by Horderf** [comment] 2024-04-10 16:19
Hi Tibor,

I'm pretty sure the DIP switches will be in the correct positions when I check tomorrow. Should the parameter (Port: -1) of the PSD/4SF valve_input  be the same as the parameter (Port: -1) of the PSD/4SF valve_output? Doesn't it make more sense to be 0 or +1 given it's a Y valve?

***@***.***

Best,

Adrian

**Comment by fuzikt** [comment] 2024-04-11 14:59
Dear Adrian,

on my pump setup the DIP switches are all in off position (4,5,6 for the valve; the rest for correct setup of the pump).

- "valve_input" will send a command "I" to the pump
- "valve_output" will send a command "O" to the pump

if port is set to -1 then only "I" or "O" is sent.
if port is set to any other numerical value then "Ix" or "Ox" is sent, where the x=numerical value of the port

The pump interprets which port is the "I" and which is the "O", depending on the initialization command.

If initialized with output valve left and Y valve:
"I" -  will connect the syringe port to right valve port
"O" - will connect the syringe port to left valve port
bypass/extra - will connect the left and right port (and nothing connected to syringe port)

This you can all look up in the technical manual of the pump/mvp valve. In the program step description (bottom part of the add/edit step window) you also get a hint which command is connected to which one (e.g. valve_input => "I")

For the "Ix", "Ox":

Form the manual (PSD-6_Rev_C_Technical_manual.pdf):
5.4 Valve commands:
Ix - Move Valve to Input Position
I without x parameter moves the valve to the input position set by the Y and Z Initialize Commands.
Parameter — Input position where x = valve position 1 – 8 on multi-port valves.

Ox - Move Valve to Output Position
O without x parameter moves the valve to the output position set by the Y and Z commands.
Parameter — Output position where x = valve position 1 – 8 on multi-port valves.
See Table 2-1 input/output port location.

All the best

Tibor

**Closed as completed** 2024-08-20 12:48 UTC
Labels: bug
